name: develop
on:
  push:
    branches:
    - develop/*
  pull_request:
    branches:
    - release/*
  workflow_dispatch:

env:
  JAVAVERSION: 21.0.8
  ZULUVERSION: 21.44.17
  GRADLEVERSION: 9.0.0
    
jobs:
  build:
    runs-on: build
    steps:
      - uses: actions/checkout@v4

      - name: Prepare JDK
        id: preparejava
        run: |
          APP_DIR="${HOME}/.local/programs/java"
          JAVA_PACKAGE=zulu${ZULUVERSION}-ca-fx-jdk${JAVAVERSION}-linux_x64
          JDK_DIR="${APP_DIR}/${JAVA_PACKAGE}"
          if [ ! -d "${JDK_DIR}" ]
          then
              mkdir -p "${JDK_DIR}"
              wget -O "${HOME}/java.tar.gz" -q "https://cdn.azul.com/zulu/bin/${JAVA_PACKAGE}.tar.gz"
              tar -x -f "${HOME}/java.tar.gz" -C "${APP_DIR}"
              rm "${HOME}/java.tar.gz"
          else
              echo "Java ${JAVAVERSION} is already installed."
          fi
          echo "JAVA_HOME=${JDK_DIR}" >> $GITHUB_ENV
      
      - name: Prepare Gradle
        id: preparegradle
        run: |
          BASE_DIR="${HOME}/.local/programs/gradle"
          DIRNAME=gradle-${GRADLEVERSION}
          PACKAGE=${DIRNAME}-bin
          APP_DIR="${BASE_DIR}/${DIRNAME}"
          if [ ! -d "${BASE_DIR}" ]; then mkdir -p "$BASE_DIR"; fi
          if [ ! -d "${APP_DIR}" ]
          then
              wget -O "${HOME}/gradle.zip" -q "https://downloads.gradle.org/distributions/${PACKAGE}.zip"
              unzip -q "${HOME}/gradle.zip" -d "${BASE_DIR}"
              rm "${HOME}/gradle.zip"
          else
              echo "Gradle ${GRADLEVERSION} is already installed."
          fi
          echo "GRADLE_HOME=${APP_DIR}" >> $GITHUB_ENV
      - name: Setting build properties
        run: |
          echo "${{ vars.BUILD_APPLICATION_PROPERTIES }}" > "src/test/resources/application-test.properties"
          cat "src/test/resources/application-test.properties"
      - name: Build application
        run: |
          PATH="${JAVA_HOME}/bin:${GRADLE_HOME}/bin:${PATH}"
          V=$(git rev-parse --abbrev-ref HEAD | sed -E 's/(.*)\/(.*)/\2/g')
          H="$(git rev-parse --short HEAD)"
          VERS="${V}-beta-${H}"
          gradle -Pversion="${VERS}" clean distribute
          echo "VERS=${VERS}" > $GITHUB_ENV
      - name: Create archive
        run: |
          ARC="${PWD}/build/dist/tools-${VERS}.tar.gz"
          DIR="${PWD}/build/dist/libs"
          (cd "${DIR}" && tar -czf "${ARC}" *.jar)
      - name: Publish archive
        run: |
          IDFILE="${HOME}/.ssh/$(uuidgen)"
          echo "${{ secrets.SSH_FOO_HETZNER }}" > "${IDFILE}"
          chmod 600 "${IDFILE}"
          cat "${IDFILE}"
          rm "${IDFILE}"