name: release
on:
  push:
    branches:
    - release/*
  workflow_dispatch:

jobs:
  build:
    runs-on: build
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo "Building"
